
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird - CI Workflow

    on:
      workflow_dispatch:
      pull_request:
        branches:
          - main
          - master
        types: [opened, reopened, labeled, unlabeled, synchronize, closed]
        paths:
          - 'add_new_column_with_values/**'

    concurrency: ${{ github.workflow }}-${{ github.event.pull_request.number }}

    jobs:
        ci: # ci using branches from workspace 'add_new_column_with_values'
          uses: tinybirdco/ci/.github/workflows/ci.yml@400
          with:
            data_project_dir: add_new_column_with_values
          secrets:
            tb_admin_token: ${{ secrets.TB_ADMIN_TOKEN_ADD_NEW_COLUMN_WITH_VALUES }}  # set the Workspace admin token in GitHub secrets
            tb_host: https://ui.tinybird.co
