
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird - CI Workflow

    on:
      workflow_dispatch:
      pull_request:
        branches:
          - main
          - master
        types: [opened, reopened, labeled, unlabeled, synchronize, closed]
        paths:
          - 'add_nullable_column_to_landing_data_source/**'

    concurrency: ${{ github.workflow }}-${{ github.event.pull_request.number }}

    jobs:
        ci:
          uses: tinybirdco/ci/.github/workflows/ci.yml@v4.0.0
          with:
            data_project_dir: add_nullable_column_to_landing_data_source
          secrets:
            tb_admin_token: ${{ secrets.TB_ADMIN_TOKEN_ADD_NULLABLE_COLUMN_LANDING_DS }}  # set the Workspace admin token in GitHub secrets
            tb_host: https://api.tinybird.co
