
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird - CD Workflow

    on:
      workflow_dispatch:
      push:
        paths:
          - 'add_new_column_to_a_materialized_view/**'
        branches:
          - main
    jobs:
      cd:
        uses: tinybirdco/ci/.github/workflows/cd.yml@main
        with:
          data_project_dir: ./add_new_column_to_a_materialized_view
        secrets:
          tb_admin_token: ${{ secrets.TB_ADMIN_TOKEN_ADD_COLUMN_TO_MATERIALIZED_VIEW }}
          tb_host: https://api.tinybird.co
