
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird - CI Workflow

    on:
      workflow_dispatch:
      pull_request:
        paths:
          - 'add_new_column_to_a_materialized_view/**'
        branches:
         - main
        types: [opened, reopened, labeled, unlabeled, synchronize, closed]

    concurrency: ${{ github.workflow }}-${{ github.event.pull_request.number }}

    jobs:
        ci:
          uses: tinybirdco/ci/.github/workflows/ci.yml@400
          with:
            data_project_dir: ./add_new_column_to_a_materialized_view
          secrets:
            tb_admin_token: ${{ secrets.TB_ADMIN_TOKEN_ADD_COLUMN_TO_MATERIALIZED_VIEW }}
            tb_host: https://api.tinybird.co
