
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird - CD Workflow

    on:
      workflow_dispatch:
      push:
        paths:
          - 'change_sorting_key_to_kafka_data_source/**'
        branches:
          - main
    jobs:
      cd:
        uses: tinybirdco/ci/.github/workflows/cd.yml@main
        with:
          tb_deploy: false
          data_project_dir: ./change_sorting_key_to_kafka_data_source
        secrets:
          tb_admin_token: ${{ secrets.TB_ADMIN_CHANGE_SORTING_KEY_TO_KAFKA_DATA_SOURCE }}
          tb_host: https://api.tinybird.co
