
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird - CD Workflow

    on:
      workflow_dispatch:
      push:
        paths:
          - 'change_ttl/**'
        branches:
          - main
    jobs:
      cd:
        uses: tinybirdco/ci/.github/workflows/cd.yml@main
        with:
          tb_deploy: false
          data_project_dir: ./change_ttl
        secrets:
          tb_admin_token: ${{ secrets.TB_ADMIN_TOKEN_CHANGE_TTL}}
          tb_host: https://api.tinybird.co
