
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird - CD Workflow

    on:
      workflow_dispatch:
      push:
        branches:
          - main
          - master
        paths:
          - 'change_column_type_materialized_view/**'
    jobs:
      cd:
        uses: tinybirdco/ci/.github/workflows/cd.yml@main
        with:
          tb_deploy: true
          data_project_dir: change_column_type_materialized_view
        secrets:
          tb_admin_token: ${{ secrets.TB_ADMIN_CHANGE_COLUMN_TYPE_MATERIALIZED_VIEW }}  # set the Workspace admin token in GitHub secrets
          tb_host: https://api.tinybird.co
