
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird - CI Workflow

    on:
      workflow_dispatch:
      pull_request:
        paths:
          - 'change_sorting_key_to_s3_data_source_with_reingestion/**'
        branches:
         - main
        types: [opened, reopened, labeled, unlabeled, synchronize, closed]

    concurrency: ${{ github.workflow }}-${{ github.event.pull_request.number }}

    jobs:
        ci:
          uses: tinybirdco/ci/.github/workflows/ci.yml@main
          with:
            data_project_dir: ./change_sorting_key_to_s3_data_source_with_reingestion
          secrets:
            tb_admin_token: ${{ secrets.TB_ADMIN_TOKEN_CHANGE_SORTING_KEY_TO_S3_DATA_SOURCE_WITH_REINGESTION }}
            tb_host: https://api.tinybird.co
