
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird - Releases Workflow

    on:
      workflow_dispatch:
        inputs:
          job_to_run:
            description: 'Select the job to run manually'
            required: true
            default: 'promote'

    jobs:
      cd:
        uses: tinybirdco/ci/.github/workflows/release.yml@2.0.0-release
        with:
          job_to_run: ${{ inputs.job_to_run }}
          data_project_dir: ./change_sorting_key_landing_data_source
          tb_deploy: true
        secrets:
          tb_admin_token: ${{ secrets.TB_ADMIN_TOKEN_CHANGE_SORTING_KEY_LANDING_DATA_SOURCE }}  # set the Workspace admin token in GitHub secrets
          tb_host: https://api.tinybird.co
