
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird - CD Workflow

    on:
      workflow_dispatch:
      push:
        branches:
          - main
          - master
        paths:
          - 'change_sorting_key_kafka_data_source/**'
    jobs:
      cd:
        uses: tinybirdco/ci/.github/workflows/cd.yml@main
        with:
          tb_deploy: true
          data_project_dir: change_sorting_key_kafka_data_source
        secrets:
          tb_admin_token: ${{ secrets.TB_ADMIN_TOKEN_CHANGE_SORTING_KEY_TO_KAFKA_DATA_SOURCE }}  # set the Workspace admin token in GitHub secrets
          tb_host: https://api.tinybird.co
