
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird - CI Workflow

    on:
      workflow_dispatch:
      pull_request:
        paths:
          - 'change_copy_pipe/**'
        branches:
         - main
        types: [opened, reopened, labeled, unlabeled, synchronize, closed]

    concurrency: ${{ github.workflow }}-${{ github.event.pull_request.number }}

    jobs:
        ci:
          uses: tinybirdco/ci/.github/workflows/ci.yml@main
          with:
            data_project_dir: ./change_copy_pipe
          secrets:
            tb_admin_token: ${{ secrets.TB_ADMIN_TOKEN_CHANGE_COPY_PIPE }}
            tb_host: https://api.tinybird.co
