
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird - CD Workflow

    on:
      workflow_dispatch:
      push:
        paths:
          - 'create_a_materialized_view_batch_ingest/**'
        branches:
          - main
    jobs:
      cd:
        uses: tinybirdco/ci/.github/workflows/cd.yml@main
        with:
          data_project_dir: ./create_a_materialized_view_batch_ingest
        secrets:
          tb_admin_token: ${{ secrets.TB_ADMIN_CREATE_A_MATERIALIZED_VIEW_BATCH_INGEST }}
          tb_host: https://api.us-east.tinybird.co