
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird - CI Workflow

    on:
      workflow_dispatch:
      pull_request:
        paths:
          - 'create_a_materialized_view_batch_ingest/**'
        branches:
         - main
        types: [opened, reopened, labeled, unlabeled, synchronize, closed]

    concurrency: ${{ github.workflow }}-${{ github.event.pull_request.number }}

    jobs:
        ci:
          uses: tinybirdco/ci/.github/workflows/ci.yml@main
          with:
            data_project_dir: ./create_a_materialized_view_batch_ingest
          secrets:
            tb_admin_token: ${{ secrets.TB_ADMIN_CREATE_A_MATERIALIZED_VIEW_BATCH_INGEST }}
            tb_host: https://api.us-east.tinybird.co
