
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird - CD Workflow

    on:
      workflow_dispatch:
      push:
        paths:
          - 'add_column_to_s3_ds/**'
        branches:
          - main
    jobs:
      cd:
        uses: tinybirdco/ci/.github/workflows/cd.yml@v4.0.1
        with:
          data_project_dir: ./create_s3_datasource
        secrets:
          tb_admin_token: ${{ secrets.TB_ADMIN_TOKEN_CREATE_S3_DS }}
          tb_host: https://api.tinybird.co
