
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird - CD Workflow

    on:
      workflow_dispatch:
      push:
        branches:
          - main
          - master
        paths:
          - 'create_pipe_sink/**'
    jobs:
      cd:  # deploy changes to workspace 'create_pipe_sink'
        uses: tinybirdco/ci/.github/workflows/cd.yml@v3.1.0
        with:
          data_project_dir: create_pipe_sink
        secrets:
          tb_admin_token: ${{ secrets.TB_ADMIN_CREATE_PIPE_SINK_TOKEN }}  # set the Workspace admin token in GitHub secrets
          tb_host: https://ui.us-east.tinybird.co
