
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird - CD Workflow

    on:
      workflow_dispatch:
      push:
        paths:
          - 'delete_simple_resource/**'
        branches:
          - main
    jobs:
      cd:
        uses: tinybirdco/ci/.github/workflows/cd.yml@v4.0.0
        with:
          data_project_dir: ./delete_simple_resource
        secrets:
          tb_admin_token: ${{ secrets.TB_ADMIN_TOKEN_DELETE_SIMPLE_RESOURCE }}
          tb_host: https://api.tinybird.co
