
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird - CD Workflow

    on:
      workflow_dispatch:
      push:
        paths:
          - 'how_to_rollback/**'
        branches:
          - main
    jobs:
      cd:
        uses: tinybirdco/ci/.github/workflows/cd.yml@v4.0.0
        with:
          data_project_dir: ./how_to_rollback
        secrets:
          tb_admin_token: ${{ secrets.TB_ADMIN_TOKEN_HOW_TO_ROLLBACK }}
          tb_host: https://api.tinybird.co
