
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird - CI Workflow

    on:
      workflow_dispatch:
      pull_request:
        paths:
          - 'how_to_rollback/**'
        branches:
         - main
        types: [opened, reopened, labeled, unlabeled, synchronize, closed]

    concurrency: ${{ github.workflow }}-${{ github.event.pull_request.number }}

    jobs:
        ci:
          uses: tinybirdco/ci/.github/workflows/ci.yml@main
          with:
            data_project_dir: ./how_to_rollback
          secrets:
            tb_admin_token: ${{ secrets.TB_ADMIN_TOKEN_HOW_TO_ROLLBACK }}
            tb_host: https://api.tinybird.co
