
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird - CD Workflow

    on:
      workflow_dispatch:
      push:
        branches:
          - main
          - master
        paths:
          - 'recover_data_from_quarantine/**'
    jobs:
      cd:
        uses: tinybirdco/ci/.github/workflows/cd.yml@v4.0.0
        with:
          data_project_dir: ./recover_data_from_quarantine/*
        secrets:
          tb_admin_token: ${{ secrets.TB_ADMIN_TOKEN_QUARANTINE_V3 }}  # set the Workspace admin token in GitHub secrets
          tb_host: https://api.tinybird.co
