
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird - CI Workflow

    on:
      workflow_dispatch:
      pull_request:
        branches:
          - main
          - master
        types: [opened, reopened, labeled, unlabeled, synchronize, closed]
        paths:
          - 'recover_data_from_quarantine/**'

    concurrency: ${{ github.workflow }}-${{ github.event.pull_request.number }}

    jobs:
        ci: # ci using environments from workspace 'quarentine'
          uses: tinybirdco/ci/.github/workflows/ci.yml@main
          with:
            tb_deploy: true
            data_project_dir: recover_data_from_quarantine
          secrets:
            tb_admin_token: ${{ secrets.TB_ADMIN_TOKEN_QUARANTINE_V3 }}  # set the Workspace admin token in GitHub secrets
            tb_host: https://api.tinybird.co
