
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird - CI Workflow

    on:
      workflow_dispatch:
      pull_request:
        branches:
          - main
          - master
        types: [opened, reopened, labeled, unlabeled, synchronize, closed]
        paths:
          - 'remove_column_landing_data_source/**'

    concurrency: ${{ github.workflow }}-${{ github.event.pull_request.number }}

    jobs:
        ci: # ci using environments from workspace 'quarentine'
          uses: tinybirdco/ci/.github/workflows/ci.yml@main
          with:
            tb_deploy: true
            data_project_dir: remove_column_landing_data_source
          secrets:
            tb_admin_token: ${{ secrets.TB_ADMIN_REMOVE_COLUMN_LANDING_DATA_SOURCE }}  # set the Workspace admin token in GitHub secrets
            tb_host: https://api.tinybird.co
