
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird - CD Workflow

    on:
      workflow_dispatch:
      push:
        branches:
          - main
          - master
        paths:
          - 'remove_column_landing_data_source/**'
    jobs:
      cd:
        uses: tinybirdco/ci/.github/workflows/cd.yml@main
        with:
          data_project_dir: remove_column_landing_data_source
        secrets:
          tb_admin_token: ${{ secrets.TB_ADMIN_REMOVE_COLUMN_LANDING_DATA_SOURCE }}  # set the Workspace admin token in GitHub secrets
          tb_host: https://api.tinybird.co
