
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird - CD Workflow

    on:
      workflow_dispatch:
      push:
        branches:
          - main
          - master
        paths:
          - 'add_column_with_values/**'
    jobs:
      cd:  # deploy changes to workspace 'add_column_with_values'
        uses: tinybirdco/ci/.github/workflows/cd.yml@main
        with:
          data_project_dir: add_column_with_values
        secrets:
          tb_admin_token: ${{ secrets.TB_ADMIN_TOKEN }}  # set the Workspace admin token in GitHub secrets
          tb_host: https://ui.tinybird.co
