
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird - CD Workflow

    on:
      workflow_dispatch:
      push:
        branches:
          - main
          - master
        paths:
          - 'v3/add_column_BQ_ds/**/*'
          - 'v3/add_column_BQ_ds/*'
    jobs:
      cd:  # deploy changes to workspace 'v3__add_column_bq_ds'
        uses: tinybirdco/ci/.github/workflows/cd.yml@feature/v3_using_tb_deploy
        with:
          tb_deploy: true
          data_project_dir: v3/add_column_BQ_ds
        secrets:
          tb_admin_token: ${{ secrets.TB_ADMIN_TOKEN_V3_ADD_COLUMN_BQ_DS }}  # set the Workspace admin token in GitHub secrets
          tb_host: https://api.tinybird.co
