
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird - Releases Workflow

    on:
      workflow_dispatch:
        inputs:
          job_to_run:
            description: 'Select the job to run manually'
            required: true
            default: 'promote'

    jobs:
      cd:  # manage releases for workspace 'v3__add_column_bq_ds'
        uses: tinybirdco/ci/.github/workflows/release.yml@feature/v3_using_tb_deploy
        with:
          job_to_run: ${{ inputs.job_to_run }}
          data_project_dir: v3/add_column_BQ_ds
          tb_deploy: true
        secrets:
          tb_admin_token: ${{ secrets.TB_ADMIN_TOKEN_V3_ADD_COLUMN_BQ_DS }}  # set the Workspace admin token in GitHub secrets
          tb_host: https://api.tinybird.co
