
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird - CI Workflow

    on:
      workflow_dispatch:
      pull_request:
        branches:
          - main
          - master
        types: [opened, reopened, labeled, unlabeled, synchronize, closed]
        paths:
          - 'v3/add_column_BQ_ds/**/*'
          - 'v3/add_column_BQ_ds/*'

    concurrency: ${{ github.workflow }}-${{ github.event.pull_request.number }}

    jobs:
        ci: # ci using environments from workspace 'v3__add_column_bq_ds'
          uses: tinybirdco/ci/.github/workflows/ci.yml@feature/v3_using_tb_deploy
          with:
            data_project_dir: v3/add_column_BQ_ds
          secrets:
            tb_admin_token: ${{ secrets.TB_ADMIN_TOKEN_V3_ADD_COLUMN_BQ_DS }}  # set the Workspace admin token in GitHub secrets
            tb_host: https://api.tinybird.co
