
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird - CD Workflow

    on:
      workflow_dispatch:
      push:
        branches:
          - main
          - master
        paths:
          - 'v3_add_column_landing_ds/**'
    jobs:
      cd:  # deploy changes to workspace 'v3_add_column_landing_ds'
        uses: tinybirdco/ci/.github/workflows/cd.yml@2.0.0-release
        with:
          tb_deploy: true
          data_project_dir: v3_add_column_landing_ds
        secrets:
          tb_admin_token: ${{ secrets.TB_ADMIN_TOKEN_V3_ADD_COLUMN_LANDING_DS }}  # set the Workspace admin token in GitHub secrets
          tb_host: https://api.tinybird.co
