
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird - CI Workflow

    on:
      workflow_dispatch:
      pull_request:
        branches:
          - main
          - master
        types: [opened, reopened, labeled, unlabeled, synchronize, closed]
        paths:
          - 'v3_change_column_type_to_lowcardinality/**'

    concurrency: ${{ github.workflow }}-${{ github.event.pull_request.number }}

    jobs:
        ci: # ci using environments from workspace 'v3_change_column_type_to_lowcardinality'
          uses: tinybirdco/ci/.github/workflows/ci.yml@2.0.0-release
          with:
            tb_deploy: true
            data_project_dir: v3_change_column_type_to_lowcardinality
          secrets:
            tb_admin_token: ${{ secrets.TB_ADMIN_TOKEN_COLUMN_TYPE }}  # set the Workspace admin token in GitHub secrets
            tb_host: https://api.tinybird.co
