
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird - CD Workflow

    on:
      workflow_dispatch:
      push:
        branches:
          - main
          - master
        paths:
          - 'v3_change_sorting_key_landing/**'
    jobs:
      cd:  # deploy changes to workspace 'v3_change_sorting_key_landing'
        uses: tinybirdco/ci/.github/workflows/cd.yml@2.0.0-release
        with:
          tb_deploy: true
          data_project_dir: v3_change_sorting_key_landing
        secrets:
          tb_admin_token: ${{ secrets.TB_ADMIN_TOKEN_CHANGE_SORTING_KEY_LANDING_V3 }}  # set the Workspace admin token in GitHub secrets
          tb_host: https://api.tinybird.co
