
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird - CD Workflow

    on:
      workflow_dispatch:
      push:
        branches:
          - main
          - master
        paths:
          - 'v3_delete_column_materialized_view/**'
    jobs:
      cd:  # deploy changes to workspace 'v3_delete_column_materialized_view'
        uses: tinybirdco/ci/.github/workflows/cd.yml@2.0.0-release
        with:
          tb_deploy: true
          data_project_dir: v3_delete_column_materialized_view
        secrets:
          tb_admin_token: ${{ secrets.TB_ADMIN_TOKEN_DELETE_COLUMN }}  # set the Workspace admin token in GitHub secrets
          tb_host: https://api.tinybird.co
