
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird - CD Workflow

    on:
      workflow_dispatch:
      push:
        branches:
          - main
          - master
        paths:
          - 'v3/Quarentine_V3/**'
    jobs:
      cd:
        uses: tinybirdco/ci/.github/workflows/cd.yml@main
        with:
          tb_deploy: true
          data_project_dir: v3/Quarentine_V3
        secrets:
          tb_admin_token: ${{ secrets.TB_ADMIN_TOKEN_QUARANTINE_V3 }}  # set the Workspace admin token in GitHub secrets
          tb_host: https://api.tinybird.co
